app = "realtimechat"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
PORT = "8080"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0
[http_service.concurrency]
type = "connections"
hard_limit = 1000
soft_limit = 500
